#!/usr/bin/python

import os
import sys

qemu_bin = "/usr/libexec/qemu-kvm"
qemu_argv = [ qemu_bin ]

if not "-no-kvm" in sys.argv:
    qemu_argv += [ "-no-kvm" ]

qemu_argv += filter(lambda x: x != "-enable-kvm", sys.argv[1:])
os.execv(qemu_bin, qemu_argv)
