archs:
  - ppc64le:
      distributions:
        - el7
  - s390x:
      distributions:
        - fc28
  - x86_64:
      distributions:
        - el7
        - fc28

release_branches:
  master:
    - ovirt-master
  ovirt-4.2:
    - ovirt-4.2

stages:
  - build-artifacts
  - check-patch:
      archs:
        - x86_64
      substages:
        - install:
            run-if:
              file-changed:
                - 'vdsm.spec.in'
                - '*Makefile.am'
                - 'automation/*'
        - linters:
            distributions:
              - fc28
        - tests-py27:
            runtime-requirements:
              host-distro: same
        - tests-py36:
            runtime-requirements:
              host-distro: same
            distributions:
              - fc28
