# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

---
release_branches:
  master:
    - ovirt-master
  ovirt-4.3:
    - ovirt-4.3

stages:
  - build-artifacts:
      substages:
        - build-py3:
            archs:
              - x86_64:
                  distributions:
                    - el8stream
                    - rhel8
