#!/bin/sh

export CI_PYTHON="python3"
export TRAVIS_CI=1

cd /vdsm

source automation/common.sh

# Make sure we have enough loop device nodes. Using 16 devices since with 8
# devices we have random mount failures.
create_loop_devices 16
install_lvmlocal_conf

trap teardown_storage EXIT
setup_storage

echo "To run tests use: tox -e <TOX_ENV>"
echo "To list tox environments use: tox -l"

bash