#!/usr/bin/python3

# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

from __future__ import absolute_import
from __future__ import print_function

import getpass
import sys

if '-D' in sys.argv[1:]:
    print('All identities removed.')
else:
    print('Identity added: /home/%s/.ssh/id_rsa (/home/%s/.ssh/id_rsa)' %
          (getpass.getuser(), getpass.getuser()))
