#!/usr/bin/python3

# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

from __future__ import absolute_import
from __future__ import print_function

print('''SSH_AUTH_SOCK=/tmp/ssh-IWWQReDk7XZp/agent.31069; export SSH_AUTH_SOCK;
SSH_AGENT_PID=31070; export SSH_AGENT_PID;
echo Agent pid 31070;''')
