#!/usr/bin/python3
#
# Copyright 2019 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
# Refer to the README and COPYING files for full details of the license
#
import argparse
import os
import platform
import shutil
import subprocess
import sys

parser = argparse.ArgumentParser(description="Delete target")

parser.add_argument(
    "target_name",
    help="Target name")

parser.add_argument(
    "-n", "--lun-count",
    type=int,
    default=10,
    help="Number of LUNs (default 10)")

parser.add_argument(
    "-r", "--root-dir",
    default="/target",
    help="root directory (default /target)")

parser.add_argument(
    "-i", "--iqn-base",
    default="iqn.2003-01.org",
    help="iqn base name (default iqn.2003-01.org)")

args = parser.parse_args()

host_name = platform.node()
if "." in host_name:
    host_name = host_name.split(".", 1)[0]

target_iqn = args.iqn_base + "." + host_name + "." + args.target_name
target_dir = os.path.join(args.root_dir, args.target_name)

print()
print("Deleting target")
print("  target_name:   %s" % args.target_name)
print("  target_iqn:    %s" % target_iqn)
print("  target_dir:    %s" % target_dir)
print("  lun_count:     %s" % args.lun_count)
print()

reply = input("Delete target? [N/y]: ")

if reply.strip().lower() != "y":
    sys.exit(0)

print("Deleting disks")
fileio_path = "/backstores/fileio"

for n in range(args.lun_count):
    file_name = "%02d" % n
    file_path = os.path.join(target_dir, file_name)
    backstore_name = args.target_name + "-" + file_name
    backstore_path = os.path.join(fileio_path, backstore_name)

    print("Deleting backing store %r" % backstore_path)
    subprocess.check_call(["targetcli", fileio_path, "delete", backstore_name])

print("Deleting target %r" % target_iqn)
subprocess.check_call(["targetcli", "/iscsi", "delete", target_iqn])

print("Removing target directory %r" % target_dir)
shutil.rmtree(target_dir)

print("Saving configuration")
subprocess.check_call(["targetcli", "saveconfig"])

print("Target deleted successfully")
