#!/usr/bin/python3
#
# Copyright 2009-2018 Red Hat, Inc. and/or its affiliates.
#
# Licensed to you under the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.  See the files README and
# LICENSE_GPL_v2 which accompany this distribution.
#
from __future__ import absolute_import

from vdsm import vdsmd

vdsmd.main()
