#!/usr/bin/python3

# SPDX-FileCopyrightText: Red Hat, Inc. and/or its affiliates.
# SPDX-License-Identifier: GPL-2.0-or-later

from __future__ import absolute_import

from vdsm import vdsmd

vdsmd.main()
