#!/bin/sh

#
# NOTE: We don't rely on system to run logrotate for us on purpose. By
# default system invokes logrotate on daily basis, but that is not good
# enough for us. VDSM can generate large amount of logs during peek periods. 
# Therefore we prefer to run logrotate manually on a *hourly* basis.
#
# See: https://bugzilla.redhat.com/1113264
#
/usr/sbin/logrotate /etc/vdsm/logrotate/vdsm

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi

if [ -d /var/log/core ] ; then
    /usr/bin/find /var/log/core -type f -name '*xz' -mtime +7 -exec /bin/rm -f '{}' \;
    EXITVALUE=$?
    if [ $EXITVALUE != 0 ]; then
        /usr/bin/logger -t logrotate "ALERT clean old core files exited abnormally with [$EXITVALUE]"
    fi
fi

if [ -d /var/log/vdsm/import ] ; then
    /usr/bin/find /var/log/vdsm/import -type f -mtime +30 -exec /bin/rm -f '{}' \;
    EXITVALUE=$?
    if [ $EXITVALUE != 0 ]; then
        /usr/bin/logger -t logrotate "ALERT clean of old import log files exited abnormally with [$EXITVALUE]"
    fi
fi

exit $EXITVALUE
