#!/bin/sh

/usr/sbin/logrotate /etc/logrotate.d/vdsm

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT clean old core files exited abnormally with [$EXITVALUE]"
fi

exit $EXITVALUE
