FROM centos:8

# Add runtime dependencies.
RUN  dnf install -y \
    http://resources.ovirt.org/pub/yum-repo/ovirt-release-master.rpm \
    && \
    dnf update -y \
    && \
    dnf install -y \
        iproute-tc \
        nmstate \
        python3-libnl3 \
        python3-netaddr \
        python3-libselinux \
        python3-devel \
        python3-pip \
    && \
    dnf clean all

# Add pytest
RUN python3 -m pip install pytest==4.6.5

CMD ["/usr/sbin/init"]
