FROM centos:8

# Add runtime dependencies.
RUN dnf update -y \
    && \
    dnf install -y \
        iproute-tc \
        python3-libnl3 \
        python3-dbus \
        python3-netaddr \
        python3-libselinux \
        python3-devel \
        python3-pip \
    && \
    dnf clean all

# Add pytest
RUN python3 -m pip install pytest==4.6.5

CMD ["/usr/sbin/init"]
