FROM centos/centos:stream8

# Add runtime dependencies.
RUN dnf install -y \
    http://resources.ovirt.org/pub/yum-repo/ovirt-release-master.rpm \
    && \
    dnf install -y \
        autoconf \
        automake \
        dnsmasq \
        git \
        make \
        python3-devel \
        python3-pip \
        # Install vdsm-network for its dependencies
        vdsm-network \
    && \
    dnf remove -y --noautoremove vdsm-network \
    && \
    dnf clean all

# Add pytest
RUN python3 -m pip install pytest

CMD ["/usr/sbin/init"]
