# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

Vagrant.configure("2") do |config|
  config.vm.box = "nirs/vdsm-almalinux-8"
  config.vm.hostname = "al8.local"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.push.define "local-exec" do |push|
    push.script = "~/bin/git-sync"
    push.args = "al8"
  end
end
