#!/usr/bin/python3

# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

from __future__ import absolute_import

import hooking
import os
import sys

if 'localdisk' in os.environ:
    hooking.log("localdisk-hook: Cannot migrate VM with local disk")
    sys.exit(2)
