# SPDX-FileCopyrightText: Red Hat, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later

name: OST

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  trigger-ost:
    uses: oVirt/ovirt-system-tests/.github/workflows/ost.yaml@master
